base/urls.py
from django.conf.urls import url, include
from zip_codes.views import index


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^zip/', include('zip_codes.urls')),
    url(r'^luis/', include('luis.urls'))

]

luis/urls.py
from django.conf.urls import url
from luis.views import get_luis_answer


app_name = 'luis'
urlpatterns = [
    url(r'^get-answer/$', get_luis_answer, name='get-luis-answer')
]

zip_codes/urls.py
from django.conf.urls import url
from zip_codes.views import get_coordinates


app_name = 'zip_codes'
urlpatterns = [
    url(r'^get-coordinates/$', get_coordinates, name='get-coordinates')
]

luis/models.py
from django.db import models

# Create your models here.

luis/views.py
from django.shortcuts import render
from luis.credentials import luis_api_key, luis_url
from logging.handlers import TimedRotatingFileHandler
import logging
import requests


formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")

handler = TimedRotatingFileHandler('logs/app.log', when="midnight", interval=1)
handler.setFormatter(formatter)

logger = logging.getLogger("LuisApp")
handler.suffix = "%Y-%m-%d.log"
logger.addHandler(handler)
logger.setLevel(logging.INFO)


def get_luis_answer(request):
    headers = {
        'Ocp-Apim-Subscription-Key': luis_api_key,
    }

    params = {
        'q': request.POST.get('luis_query'),
        'timezoneOffset': '0',
        'verbose': 'false',
        'spellCheck': 'false',
        'staging': 'false',
    }

    try:
        logger.info("Sent query to LUIS - " + request.POST.get('luis_query'))
        r = requests.get(luis_url, headers=headers, params=params)
        json_response = r.json()
        logger.info("Response from LUIS - " + str(json_response['topScoringIntent']['intent']))
        context = {'intent': json_response}

    except Exception as e:
        context = {'error': e}
        logger.error(e)

    return render(request, 'luis/luis_answer.html', context)

zip_codes/views.py
from django.shortcuts import render
from pyzipcode import ZipCodeDatabase


def index(request):
    return render(request, 'zip_codes/index.html')


def get_coordinates(request):
    zcdb = ZipCodeDatabase()
    try:
        zipcode = zcdb[request.POST.get('zip_code')]
        coordinates = {
            'zip_code': zipcode.zip,
            'longitude': zipcode.longitude,
            'latitude': zipcode.latitude
        }
        context = {'coordinates': coordinates}
    except Exception as e:
        context = {'error': e}

    return render(request, 'zip_codes/coordinates.html', context)

luis/templates/luis/luis_answer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LUIS intent</title>
</head>
<body>
    {% if intent %}
        <p>Intent Name - {{ intent.topScoringIntent.intent }}</p>
    {% else%}
        <p>{{ error }}</p>
    {% endif %}
    <a href="/">Back</a>
</body>
</html>

zip_codes/templates/zip_codes/coordinates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coordinates</title>
</head>
<body>
    {% if coordinates %}
        <p>Your ZIP code - {{ coordinates.zip_code }}</p>
        <p>Longitude: {{ coordinates.latitude }}</p>
        <p>Latitude: {{ coordinates.longitude}}</p>
    {% else %}
        <p>{{ error }}</p>
    {% endif %}
</body>
</html>

zip_codes/templates/zip_codes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test task</title>
</head>
<body>

    <form action="{% url 'zip_codes:get-coordinates' %}" method="POST">
         {% csrf_token %}
         <p> Enter your Zip code (f.e. 10013)</p>
         <input type="number" name="zip_code" min="1" value="1">
         <button type="submit">Get coordinates</button>
    </form>
    <hr>
    <form action="{% url 'luis:get-luis-answer' %}" method="POST">
         {% csrf_token %}
         <p> Enter your query for LUIS</p>
         <input type="text" name="luis_query">
         <button type="submit">Get intent</button>
    </form>
</body>
</html>